name: Flake8 Lint

on:
  push:
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: [3.9, 3.10, 3.11, 3.12]
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 . --config .flake8 --count --select=E9,F63,F7,F82 --show-source --statistics 